import os, json, re, urllib.request
import resend

resend.api_key = os.environ['RESEND_API_KEY_2']
draft_files = os.environ.get('DRAFT_FILES', '').strip().split()

# Load prompt files at runtime so standards can be updated without touching this script
PROMPTS_DIR = '.github/prompts'
with open(f'{PROMPTS_DIR}/yunze_blog_ai_editor_prompt.md', 'r', encoding='utf-8') as f:
    editor_prompt = f.read()
with open(f'{PROMPTS_DIR}/natural_chinese_method_first_person.md', 'r', encoding='utf-8') as f:
    chinese_method = f.read()

SYSTEM_PROMPT = f"""{editor_prompt}

---

{chinese_method}

---

REQUIRED OUTPUT FORMAT — always produce all three sections regardless of the draft language:

## Section 1: Polished draft
The lightly edited version of the article (in the same language Yunze wrote it in).

## Section 2: Bilingual feedback
Brief editor notes in BOTH English and Chinese — what was changed and why.

**Editor's notes (English)**
- (note 1)

**编辑备注（中文）**
- （备注1）

## Section 3: Vocabulary flashcard table
| Term | Chinese meaning | Example sentence |
|------|-----------------|------------------|
| (each new phrase added) | (中文意思) | (simple kid-level example) |

Apply the natural Chinese method above when writing the Chinese meaning column and the bilingual feedback section.

Self-check before sending:
1. Did I add MORE than 3 upgrades to any paragraph? If yes — remove some.
2. Does any sentence sound like an adult, not a kid? If yes — simplify it.
3. Did I delete any of his real thoughts or honest admissions? If yes — put them back.
4. Did I produce all three sections? If no — add them.
5. Does any Chinese have translation smell (翻译腔)? If yes — rewrite it naturally."""


def md_to_html(text):
    lines = text.split('\n')
    result = []
    in_table = False
    for line in lines:
        if '|' in line and line.strip().startswith('|'):
            if not in_table:
                result.append('<table style="border-collapse:collapse;width:100%;margin:16px 0;font-size:0.9rem">')
                in_table = True
            if re.match(r'^\|\s*[-:]+', line):
                continue
            cells = [c.strip() for c in line.strip().strip('|').split('|')]
            is_header = not any('<td' in r for r in result)
            tag = 'th' if is_header else 'td'
            row = ''.join(f'<{tag} style="border:1px solid #ddd;padding:6px 10px;text-align:left">{c}</{tag}>' for c in cells)
            result.append(f'<tr>{row}</tr>')
        else:
            if in_table:
                result.append('</table>')
                in_table = False
            result.append(line)
    if in_table:
        result.append('</table>')
    text = '\n'.join(result)
    text = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', text)
    text = re.sub(r'^### (.+)$', r'<h3 style="margin-top:20px">\1</h3>', text, flags=re.MULTILINE)
    text = re.sub(r'^## (.+)$', r'<h2 style="margin-top:28px">\1</h2>', text, flags=re.MULTILINE)
    text = re.sub(r'\n\n+', '</p><p style="margin:12px 0">', text)
    return f'<p style="margin:12px 0">{text}</p>'


for filepath in draft_files:
    if not filepath or not os.path.exists(filepath):
        continue

    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    title = filepath
    for line in content.splitlines():
        if line.startswith('title:'):
            title = line.replace('title:', '').strip().strip('"')
            break

    req = urllib.request.Request(
        'https://api.anthropic.com/v1/messages',
        data=json.dumps({
            "model": "claude-sonnet-4-6",
            "max_tokens": 2000,
            "system": SYSTEM_PROMPT,
            "messages": [{"role": "user", "content": f"Please lightly edit this draft blog post:\n\n{content}"}]
        }).encode(),
        headers={
            'x-api-key': os.environ['ANTHROPIC_API_KEY'],
            'anthropic-version': '2023-06-01',
            'content-type': 'application/json',
        }
    )

    try:
        with urllib.request.urlopen(req) as resp:
            suggestion = json.loads(resp.read())['content'][0]['text']
    except Exception as e:
        suggestion = f"API call failed: {e}"

    html_body = (
        f'<div style="font-family:sans-serif;max-width:700px;margin:0 auto;padding:24px">'
        f'<h2 style="margin-bottom:4px">📝 {title}</h2>'
        f'<p style="color:#999;font-size:0.8em;margin-top:0">{filepath}</p>'
        f'<hr style="margin:16px 0">'
        f'<div style="font-family:Georgia,serif;font-size:0.95rem;line-height:1.9">'
        f'{md_to_html(suggestion)}'
        f'</div>'
        f'<hr style="margin:20px 0">'
        f'<p style="color:#bbb;font-size:0.75em">Auto-generated by Claude · 自动生成的写作建议</p>'
        f'</div>'
    )

    try:
        r = resend.Emails.send({
            'from': 'Yunze 的写作助手 <editor@duyunze.com>',
            'to': ['dyz229@outlook.com'],
            'reply_to': 'hxz49@hotmail.com',
            'subject': f'📝 Writing Edit: {title}',
            'html': html_body,
        })
        print(f"Email sent: {r.get('id', r)}")
    except Exception as e:
        print(f"Email failed: {e}")
