baseURL = "https://yunze229.github.io/"
ignoreFiles = ["static/capsule-worker/node_modules", "static/capsule-worker/package.*", "static/capsule-worker/wrangler.toml"]
locale = "zh-CN"
title = "Yunze"
theme = "yunze"
paginate = 10
enableRobotsTXT = true
enableEmoji = false

[params]
  capsule_api = "https://yunze-capsule.dyz229.workers.dev"
  description = "以逻辑解构世界，以创造交付结果"
  author = "Yunze"
  since = 2026
  goatcounter = "yunze229"
  giscus_repo = "Yunze229/yunze229.github.io"
  giscus_repo_id = "R_kgDOSeGgnQ"
  giscus_category = "Announcements"
  giscus_category_id = "DIC_kwDOSeGgnc4C9NIx"

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    noClasses = false
