baseURL = "https://duyunze.com/"
ignoreFiles = ["static/capsule-worker/node_modules", "static/capsule-worker/package.*", "static/capsule-worker/wrangler.toml"]
locale = "zh-CN"
title = "Yunze"
theme = "yunze"
paginate = 10
enableRobotsTXT = true
enableEmoji = false

[params]
  capsule_api = "https://capsule.duyunze.com"
  turnstile_site_key = "0x4AAAAAADSosVQW7GZ2FSq4"   # 填入 Cloudflare Turnstile 的 Site Key
  description = "以逻辑解构世界，以创造交付结果"
  author = "Yunze"
  since = 2026
  goatcounter = "yunze229"

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    noClasses = false
